apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  type: NodePort
  ports:
  - port: 8501
    nodePort: 30001
    protocol: TCP
  selector:
    app: streamlit
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30002
    protocol: TCP
  selector:
    app: api